name: 測試
on:
    push:
        branches: [main]
jobs:
    task_1:
        runs-on: ubuntu-latest
        steps:
            - name: 檢查當前路徑
              run: pwd

            - name: 檢查node.js 版本
              run: node -v
    task_2:
        runs-on: ubuntu-latest
        steps:
            - name: 下載repo
              run: actions/checkout@v4

            - name: 顯示所有檔案
              run: ls -R

           


